###########
# site.title

title:    'TEN7 Jekyll Starter'
subtitle: 'Here&rsquo;s a sub-title.'


nav:
- { title: 'Home',              href: '/' }
- { title: 'Our Mission',                href: 'https://ten7.com/mission' }


#########################
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md

