###########
# site.title

title: "Contractor's Quick Start"
subtitle: "Version 1.2.6, 06/22/21"

nav:
- title: "Contractor's Quick Start"
  url: "/"
- title: "FAQs"
  subfolderitems:
  - title: "Administrative"
    url: "/admin.html"
  - title: "Time Tracking and Payment"
    url: "/time.html"
  - title: "Process"
    url: "/process.html"
  - title: "Developer Specific"
    url: "/developer.html"

#########################
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md

